heat_template_version: 2013-05-23

description: >
  HOT template to creates a virtual network and subnet 

parameters:
  net_name:
    type: string
    description: Name of virtual network to be created
  shared:
    type: string
    description: Is virtual network shared
    default: False
  external:
    type: string
    description: Is virtual network external
    default: true
  subnet_name:
    type: string
    description: Name of subnet to be created
  ip_prefix:
    type: string
    description: The CIDR
  default_gateway:
    type: string
    description: The default gateway 
  ipam_name:
    type: string
    description: The assoiated IPAM id or fq_name_string
  dhcp:
    type: string
    description: Enable DHCP (True or False)
    default: True
  dns_nameservers:
    description: DNS Nameservers list
    type: comma_delimited_list
    default: 8.8.8.8
  route_targets:
    type: string
    description: route targets associated with the virtual network

resources:
  ipam:
    type: OS::Contrail::NetworkIpam
    properties:
      name: { get_param: ipam_name }
  virtual_network:
    type: OS::Contrail::VirtualNetwork
    properties:
      name: { get_param: net_name }
      route_targets: { "Fn::Split" : [ ",", Ref: route_targets ] }
      shared: { get_param: shared }
      external: { get_param: external }

  virtual_subnet:
    type: OS::Contrail::VnSubnet
    depends_on: virtual_network
    properties:
      name: { get_param: subnet_name }
      #network: { get_param: net_name }
      network: { get_resource: virtual_network }
      ip_prefix: { get_param: ip_prefix }
      default_gateway: { get_param: default_gateway }
      ipam: { get_resource: ipam }
