#!/bin/bash


args=("$@")
export OS_USERNAMEadmin
export OS_PASSWORD=contrail123
export OS_TENANT_NAME=$USER
export OS_AUTH_URL=http://controller:5000/v2.0/
export OS_NO_CACHE=1

export ROOT_DIR=$PWD
export TMPLT_DIR=$PWD/templates
export PATH=$PATH:$PWD/bin
export PORTAL_PORT=8197
