#!/bin/bash

if [[ $# -ne 1 ]]; then
	echo "Usage: setup_env tenant-name"
	echo "Example: setup_env harpo"
        exit 0
fi

export OS_USERNAME=admin
export OS_PASSWORD=contrail123
export OS_TENANT_NAME=$1
export OS_AUTH_URL=http://controller:5000/v2.0/
export OS_NO_CACHE=1

export ROOT_DIR=$PWD
export TMPLT_DIR=$PWD/templates
export PATH=$PATH:$PWD/bin
export PORTAL_PORT=8197
