heat_template_version: 2013-05-23

description: >
  HOT template to create a security group

parameters:
  sg_name:
    type: string
    description: Name of security group

resources:
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Create a security group with rules
      name: { get_param: sg_name }
      rules: [
        {
          remote_ip_prefix: 0.0.0.0/0,
          protocol: udp,
          port_range_min: 1,
          port_range_max: 65535
        },
        {
          remote_ip_prefix: 0.0.0.0/0,
          protocol: tcp,
          port_range_min: 1,
          port_range_max: 65535
        },
        {
          remote_ip_prefix: 0.0.0.0/0,
          protocol: icmp
        },
      ]

